export interface ReturnsList{
  recordsPerPage:number;
    totalRecords:number;
    pageOffset:number;
    currentPage:number;
    totalPages:number;
    pagesToDisplay:number[];
    order_id:string;
    order_number:string;
    store_name:string;
    start_date:string;
    end_date:string;
    status:number;
    total_returned_quantity:number;
    total_damaged_quantity:number;
    modifiedBy:number;
    sort_name:string;
    sort_type:string;
    isAscending:boolean;
    download:boolean
}
