
const CountryTimezones = {
  AL : 'Europe/Tirane',
  AD : 'Europe/Andorra',
  AR : 'America/Argentina/Buenos_Aires',
  AM : 'Asia/Yerevan',
  AU : {
    NSW: 'Australia/Sydney',
    VIC: 'Australia/Melbourne',
    QLD: 'Australia/Brisbane',
    WA: 'Australia/Perth',
    SA: 'Australia/Adelaide',
    TAS: 'Australia/Hobart',
    NT: 'Australia/Darwin',
    ACT: 'Australia/Canberra',
  },
  AT : 'Europe/Vienna',
  AZ : 'Asia/Baku',
  BD : 'Asia/Dhaka',
  BY : 'Europe/Minsk',
  BE : 'Europe/Brussels',
  BZ : 'America/Belize',
  BO : 'America/La_Paz',
  BA : 'Europe/Sarajevo',
  BR :{
    AC: 'America/Rio_branco',
    AL: 'America/Maceio',
    AP: 'America/Belem',
    AM: 'America/Manaus',
    BA: 'America/Bahia',
    CE: 'America/Fortaleza',
    DF: 'America/Sao_Paulo',
    ES: 'America/Sao_Paulo',
    GO: 'America/Sao_Paulo',
    MA: 'America/Fortaleza',
    MT: 'America/Cuiaba',
    MS: 'America/Campo_Grande',
    MG: 'America/Sao_Paulo',
    PA: 'America/Belem',
    PB: 'America/Fortaleza',
    PR: 'America/Sao_Paulo',
    PE: 'America/Recife',
    PI: 'America/Fortaleza',
    RJ: 'America/Sao_Paulo',
    RN: 'America/Fortaleza',
    RS: 'America/Sao_Paulo',
    RO: 'America/Porto_Velho',
    RR: 'America/Boa_Vista',
    SC: 'America/Sao_Paulo',
    SP: 'America/Sao_Paulo',
    SE: 'America/Maceio',
    TO: 'America/Araguaia',
  },
  BN : 'Asia/Brunei',
  BG : 'Europe/Sofia',
  KH : 'Asia/Phnom_Penh',
  CA :{
    NL: 'America/St_Johns',
    PE: 'America/Halifax',
    NS: 'America/Halifax',
    NB: 'America/Halifax',
    QC: 'America/Montreal',
    ON: 'America/Toronto',
    MB: 'America/Winnipeg',
    SK: 'America/Regina',
    AB: 'America/Edmonton',
    BC: 'America/Vancouver',
    YT: 'America/Whitehorse',
    NT: 'America/Yellowknife',
    NU: 'America/Iqaluit',
  },
  CL : 'America/Santiago',
  CN : 'Asia/Shanghai',
  CO : 'America/Bogota',
  CK : 'Pacific/Rarotonga',
  CR : 'America/Costa_Rica',
  HR : 'Europe/Zagreb',
  CU : 'America/Havana',
  CY : 'Asia/Nicosia',
  CZ : 'Europe/Prague',
  DK : 'Europe/Copenhagen',
  TL : 'Asia/Dili',
  EC : 'America/Guayaquil',
  SV : 'America/El_Salvador',
  EE : 'Europe/Tallinn',
  FK : 'Atlantic/Stanley',
  FM : 'Pacific/Pohnpei',
  FJ : 'Pacific/Fiji',
  FI : 'Europe/Helsinki',
  FR : 'Europe/Paris',
  GF : 'America/Cayenne',
  PF : 'Pacific/Tahiti',
  GE : 'Asia/Tbilisi',
  DE : 'Europe/Berlin',
  GI : 'Europe/Gibraltar',
  GR : 'Europe/Athens',
  GP : 'America/Guadeloupe',
  GT : 'America/Guatemala',
  GY : 'America/Guyana',
  HT : 'America/Port-au-Prince',
  HN : 'America/Tegucigalpa',
  HK : 'Asia/Hong_Kong',
  HU : 'Europe/Budapest',
  IS : 'Atlantic/Reykjavik',
  IN : 'Asia/Kolkata',
  ID : {
    WIB: 'Asia/Jakarta',
    WITA: 'Asia/Makassar',
    WIT: 'Asia/Jayapura',
  },
  IE : 'Europe/Dublin',
  IT : 'Europe/Rome',
  JP : 'Asia/Tokyo',
  KI : 'Pacific/Tarawa',
  XK : 'Europe/Belgrade',
  LA : 'Asia/Vientiane',
  LV : 'Europe/Riga',
  LI : 'Europe/Vaduz',
  LT : 'Europe/Vilnius',
  LU : 'Europe/Luxembourg',
  MO : 'Asia/Macau',
  MK : 'Europe/Skopje',
  MY : 'Asia/Kuala_Lumpur',
  MT : 'Europe/Malta',
  MH : 'Pacific/Majuro',
  MQ : 'America/Martinique',
  MX : {
    PST: 'America/Tijuana',
    MST: 'America/Chihuahua',
    CST: 'America/Mexico_City',
    EST: 'America/Cancun',
  },
  MD : 'Europe/Chisinau',
  MC : 'Europe/Monaco',
  ME : 'Europe/Podgorica',
  NR : 'Pacific/Nauru',
  NL : 'Europe/Amsterdam',
  AN : 'America/Aruba',
  NC : 'Pacific/Noumea',
  NZ : 'Pacific/Auckland',
  NI : 'America/Managua',
  NU : 'Pacific/Niue',
  KP : 'Asia/Pyongyang',
  NO : 'Europe/Oslo',
  PW : 'Pacific/Palau',
  PA : 'America/Panama',
  PG : 'Pacific/Port_Moresby',
  PY : 'America/Asuncion',
  PE : 'America/Lima',
  PH : 'Asia/Manila',
  PL : 'Europe/Warsaw',
  PT : 'Europe/Lisbon',
  RO : 'Europe/Bucharest',
  RU : {
    KALT: 'Europe/Kaliningrad',
    MSK: 'Europe/Moscow',
    SAMT: 'Europe/Samara',
    YEKT: 'Asia/Yekaterinburg',
    OMST: 'Asia/Omsk',
    KRAT: 'Asia/Krasnoyarsk',
    IRKT: 'Asia/Irkutsk',
    YAKT: 'Asia/Yakutsk',
    VLAT: 'Asia/Vladivostok',
    MAGT: 'Asia/Magadan',
    PETT: 'Asia/Kamchatka',
  },
  PM : 'America/Miquelon',
  WS : 'Pacific/Apia',
  SM : 'Europe/San_Marino',
  RS : 'Europe/Belgrade',
  SG : 'Asia/Singapore',
  SK : 'Europe/Bratislava',
  SI : 'Europe/Ljubljana',
  SB : 'Pacific/Guadalcanal',
  KR : 'Asia/Seoul',
  ES : 'Europe/Madrid',
  SR : 'America/Paramaribo',
  SE : 'Europe/Stockholm',
  CH : 'Europe/Zurich',
  TW : 'Asia/Taipei',
  TH : 'Asia/Bangkok',
  TK : 'Pacific/Fakaofo',
  TO : 'Pacific/Tongatapu',
  TR : 'Europe/Istanbul',
  TV : 'Pacific/Funafuti',
  UA : 'Europe/Kiev',
  GB : 'Europe/London',
  US : {
    AL: 'America/Chicago',
    AK: 'America/Anchorage',
    AZ: 'America/Phoenix',
    AR: 'America/Chicago',
    CA: 'America/Los_Angeles',
    CO: 'America/Denver',
    CT: 'America/New_York',
    DE: 'America/New_York',
    FL: 'America/New_York',
    GA: 'America/New_York',
    HI: 'Pacific/Honolulu',
    ID: 'America/Denver',
    IL: 'America/Chicago',
    IN: 'America/New_York',
    IA: 'America/Chicago',
    KS: 'America/Chicago',
    KY: 'America/New_York',
    LA: 'America/Chicago',
    ME: 'America/New_York',
    MD: 'America/New_York',
    MA: 'America/New_York',
    MI: 'America/New_York',
    MN: 'America/Chicago',
    MS: 'America/Chicago',
    MO: 'America/Chicago',
    MT: 'America/Denver',
    NE: 'America/Chicago',
    NV: 'America/Los_Angeles',
    NH: 'America/New_York',
    NJ: 'America/New_York',
    NM: 'America/Denver',
    NY: 'America/New_York',
    NC: 'America/New_York',
    ND: 'America/Chicago',
    OH: 'America/New_York',
    OK: 'America/Chicago',
    OR: 'America/Los_Angeles',
    PA: 'America/New_York',
    RI: 'America/New_York',
    SC: 'America/New_York',
    SD: 'America/Chicago',
    TN: 'America/Chicago',
    TX: 'America/Chicago',
    UT: 'America/Denver',
    VT: 'America/New_York',
    VA: 'America/New_York',
    WA: 'America/Los_Angeles',
    WV: 'America/New_York',
    WI: 'America/Chicago',
    WY: 'America/Denver',
  },
  UY : 'America/Montevideo',
  VU : 'Pacific/Efate',
  VA : 'Europe/Vatican',
  VE : 'America/Caracas',
  VN : 'Asia/Ho_Chi_Minh',
  WF : 'Pacific/Wallis',
}
